### ISSUE TITLE
Los mensajes borrados del foro deberían poder ser recuperados

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-domain#165]
Actualmente, cuando borramos los mensajes del foro, desaparecen para siempre. 
De esa forma, si necesitáramos de esos mensajes, ya no existen.
Habría que ver la forma de ocultarlos o darles una baja lógica para que, si bien aparezca como que no están más, estén en algún lado por si los necesitáramos.

**Comment by flbulgarelli** [comment]
Totalmente de acuerdo. Deberiamos implementar baja lógica

**Comment by luchotc** [comment]
Someone should be able to still see them in the UI (with a visual difference) and restore them.
@rgonzalezt @flbulgarelli Should it be moderators or admins?

**Comment by rgonzalezt** [comment]
I think moderators and admins should be able to still see the messages in the UI but **only admins could restore them**.

**Comment by flbulgarelli** [comment]
> I think moderators and admins should be able to still see the messages in the UI but only admins could restore them.

Agree

**Comment by luchotc** [comment]
Awesome. 
We should save a deleted_by, so we can display the name of the user who deleted it as well @julian-berbel

**Comment by felipecalvo** [comment]
This was done a couple months ago: https://github.com/mumuki/mumuki-domain/pull/206

It's not possible to restore deleted messages from the UI, though, but we could discuss adding that if needed.
